In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [3]:
air = pd.read_csv('AirQualityUCI.csv')

In [5]:
air.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10-03-2004,18:00:00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,NaN,NaN
1,10-03-2004,19:00:00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,NaN,NaN
2,10-03-2004,20:00:00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,NaN,NaN
3,10-03-2004,21:00:00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,NaN,NaN
4,10-03-2004,22:00:00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,NaN,NaN

In [7]:
air.tail()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
9466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
air.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   object
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   float64
 4   NMHC(GT)       9357 non-null   float64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   float64
 7   NOx(GT)        9357 non-null   float64
 8   PT08.S3(NOx)   9357 non-null   float64
 9   NO2(GT)        9357 non-null   float64
 10  PT08.S4(NO2)   9357 non-null   float64
 11  PT08.S5(O3)    9357 non-null   float64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
 15  Unnamed: 15    0 non-null      float64
 16  Unnamed: 16    0 non-null      float64
dtypes: float64(15), object(2)
memory usage: 1.2+ MB

In [11]:
air.shape

(9471, 17)

In [13]:
air.isnull()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9466,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9467,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9468,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9469,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9470,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [17]:
#data cleaning
air.fillna(air.mode().iloc[0],inplace=True)

In [19]:
air.describe()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
count,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,0.0,0.0
mean,-36.203125,1033.956288,-159.582515,-0.564122,881.419913,164.180023,783.013726,55.041601,1372.323408,960.927991,7.253257,36.602756,-9.162650,NaN,NaN
std,79.277658,355.011244,139.016763,46.651368,360.597975,259.018201,337.943779,129.276708,495.762597,471.912072,48.656583,57.215605,44.098134,NaN,NaN
min,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,NaN,NaN
25%,0.600000,915.000000,-200.000000,3.900000,704.000000,47.000000,631.000000,51.000000,1171.000000,689.000000,10.700000,33.500000,0.676800,NaN,NaN
50%,1.500000,1050.000000,-200.000000,7.800000,890.000000,139.000000,791.000000,95.000000,1440.000000,936.000000,17.000000,48.100000,0.971100,NaN,NaN
75%,2.600000,1218.000000,-200.000000,13.500000,1102.000000,281.500000,957.000000,132.000000,1658.000000,1250.000000,24.000000,61.700000,1.291500,NaN,NaN
max,11.900000,2040.000000,1189.000000,63.700000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,44.600000,88.700000,2.231000,NaN,NaN

In [21]:
air.drop_duplicates(inplace=True)

In [23]:
#data integration
air.columns

Index(['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)',
       'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)',
       'PT08.S5(O3)', 'T', 'RH', 'AH', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [25]:
df1 = air[['CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)']]
df2 = air[['C6H6(GT)','PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)']]
df1,df2

(      CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)
 0        2.6       1360.0     150.0      11.9
 1        2.0       1292.0     112.0       9.4
 2        2.2       1402.0      88.0       9.0
 3        2.2       1376.0      80.0       9.2
 4        1.6       1272.0      51.0       6.5
 ...      ...          ...       ...       ...
 9353     2.4       1163.0    -200.0      11.4
 9354     2.4       1142.0    -200.0      12.4
 9355     2.1       1003.0    -200.0       9.5
 9356     2.2       1071.0    -200.0      11.9
 9357  -200.0       -200.0    -200.0    -200.0

 [9358 rows x 4 columns],
       C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)
 0         11.9         1046.0    166.0        1056.0
 1          9.4          955.0    103.0        1174.0
 2          9.0          939.0    131.0        1140.0
 3          9.2          948.0    172.0        1092.0
 4          6.5          836.0    131.0        1205.0
 ...        ...            ...      ...           ...
 9353      11.4         1027.0    353.0         604.0
 9354      12.4         1063.0    293.0         603.0
 9355       9.5          961.0    235.0         702.0
 9356      11.9         1047.0    265.0         654.0
 9357    -200.0         -200.0   -200.0        -200.0

 [9358 rows x 4 columns])

In [29]:
data=pd.merge(df1,df2,on='C6H6(GT)',how='inner')
data.head(10)

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx)
0,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0
1,2.6,1360.0,150.0,11.9,1045.0,174.0,880.0
2,2.6,1360.0,150.0,11.9,1045.0,170.0,974.0
3,2.6,1360.0,150.0,11.9,1047.0,129.0,815.0
4,2.6,1360.0,150.0,11.9,1046.0,-200.0,882.0
5,2.6,1360.0,150.0,11.9,1047.0,144.0,809.0
6,2.6,1360.0,150.0,11.9,1048.0,-200.0,1016.0
7,2.6,1360.0,150.0,11.9,1046.0,177.0,838.0
8,2.6,1360.0,150.0,11.9,1046.0,146.0,777.0
9,2.6,1360.0,150.0,11.9,1045.0,207.0,761.0

In [31]:
#data transformation
air = air.astype(str)

In [33]:
encoder= LabelEncoder()
for col in air.select_dtypes(include=['object']):
    air[col]=encoder.fit_transform(air[col])

In [35]:
air.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,114,18,30,361,55,39,47,142,57,15,691,269,66,375,1896,0,0
1,114,19,24,293,17,402,1201,16,175,276,558,1716,63,363,1727,0,0
2,114,20,26,403,414,398,1185,98,141,16,554,75,49,426,1853,0,0
3,114,21,26,377,396,400,1194,149,93,25,583,204,40,486,2056,0,0
4,114,22,16,273,298,372,1082,98,205,18,489,111,42,482,2066,0,0

In [39]:
#data modeling
x = air.drop(columns=['Date','Time'])
y = air['CO(GT)']
y=y.round().astype(int)

In [41]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [43]:
model = RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [45]:
y_pred = model.predict(x_test)
y_pred

array([28, 15,  0, ...,  0, 28, 19])

In [47]:
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

0.7873931623931624

In [ ]:
#error correcting
# Fill missing numeric values with column means
df.fillna(df.mean(numeric_only=True), inplace=True)

print(" Cleaned dataset shape:", df.shape)
print(" Missing values after correction:\n", df.isna().sum())